name: liqpay
description: LiqPay payment service wrapper library to be used on a client or server side dart.
version: 0.0.1+3
homepage: https://github.com/Newgarden-Solutions/liqpay
repository: https://github.com/Newgarden-Solutions/liqpay
issue_tracker: https://github.com/Newgarden-Solutions/liqpay/issues

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  # Network
  http: ^1.1.2
  http_interceptor: ^2.0.0-beta.7

  # Security
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
