name: liqpay
description: LiqPay payment service wrapper library.
version: 0.0.1
homepage: https://github.com/Newgarden-Solutions/liqpay

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Network
  http: ^0.13.5
  http_interceptor: ^1.0.2

  # Utility
  uuid: ^3.0.6
  equatable: ^2.0.5

  # Security
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.3.0
