name: liqpay
description: LiqPay payment service wrapper library.
version: 0.0.1
homepage: https://github.com/Newgarden-Solutions/liqpay

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Network
  http: ^0.13.6
  http_interceptor: ^1.0.2

  # Utility
  uuid: ^3.0.7
  equatable: ^2.0.5

  # Security
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  mockito: ^5.4.1
